const slugify = require('../utils/slugify')
const config = require('../config')
const { generateCompletion } = require('./groqClient')

const MOCK_ARTICLES = {
  'Technology': [
    { title: 'Quantum Internet Achieves Global Scale, Ushering in Unhackable Communications', summary: 'The first fully operational quantum internet network now spans all seven continents, promising perfectly secure communications for governments, businesses, and citizens alike.', body: 'In a landmark achievement that redefines global communications, the Quantum Internet Initiative announced today that its quantum entanglement-based network now covers every inhabited continent. The network, which uses quantum key distribution (QKD) to transmit information in a manner that is physically impossible to intercept without detection, represents a 14-year effort involving over 80 nations.\n\nDr. Elena Vasquez, the initiative\'s director, described the achievement as "the most significant infrastructure project since the original internet." Unlike classical networks, where data can be copied or intercepted, quantum networks leverage the fundamental properties of quantum mechanics—any attempt to observe quantum data alters it, making eavesdropping instantly detectable.\n\nThe implications are profound. Financial institutions are already migrating sensitive transactions to the quantum layer. Governments are establishing quantum diplomatic channels. And everyday citizens will soon have access to quantum-encrypted messaging through consumer devices that have been quantum-ready since the late 2030s.\n\nCritics point to the digital divide: while 42 nations have full quantum access, developing regions face significant infrastructure gaps. The Quantum Internet Initiative has pledged $200 billion to close this gap by 2045.', confidence: 78, confidenceExplanation: 'Based on current quantum computing roadmaps, government investment trends, and the demonstrated viability of QKD networks in metropolitan areas.' },
    { title: 'Autonomous AI Agents Now Manage 90% of Global Supply Chains', summary: 'A quiet revolution has transformed logistics as AI agents coordinate manufacturing, shipping, and delivery across the planet with minimal human input.', body: 'Ten years ago, the idea that autonomous software agents would manage nearly all global logistics seemed speculative. Today, it is reality. According to the International Logistics Federation, 90.4% of all cross-border supply chain decisions are now made by AI agents that negotiate, route, and optimize in real-time.\n\nThese agents, built on large language model architectures combined with specialized optimization algorithms, communicate with each other using a standardized protocol called SupplyNet. When a factory in Vietnam needs raw materials from Brazil, AI agents on both ends negotiate price, shipping windows, and customs clearance without human intervention.\n\nThe shift has reduced global logistics costs by 34% and cut average delivery times by 52%. However, concerns about systemic risk remain. In 2041, a cascading failure in the South American grain network caused a two-week disruption that affected 14 countries. Regulators are now debating whether "human-in-the-loop" requirements should be reinstated for critical supply nodes.', confidence: 72, confidenceExplanation: 'Current trends in AI agent research, supply chain digitization, and the rapid adoption of LLM-based automation.' },
    { title: 'Consumer Brain-Computer Interfaces Hit Mainstream as Neural Link Devices Sell 50 Million Units', summary: 'Non-invasive neural interfaces have become the must-have tech of 2041, enabling thought-to-text communication, memory enhancement, and direct brain-to-device control.', body: 'When Neuralink released its first consumer product in 2035, it was a niche device for medical applications. Six years later, brain-computer interfaces (BCIs) have gone fully mainstream. Industry analyst firm TechVision reports that 50 million BCI units were sold in the past year alone—a 300% increase from 2040.\n\nThe breakthrough came from two developments: non-invasive sensors that can read neural signals through the skull with high fidelity, and AI decoders that can interpret brain activity patterns with 99.7% accuracy. Users now compose messages by thinking, control smart home devices with intention, and even enhance memory formation.\n\nEthicists have raised alarms about neural privacy. "Your thoughts should be your own," argues Dr. Marcus Chen of the Digital Rights Foundation. Several jurisdictions have passed "neural rights" laws prohibiting unauthorized access to brain data.', confidence: 65, confidenceExplanation: 'BCI technology is progressing rapidly but consumer adoption timelines remain uncertain.' },
    { title: 'Edge Computing Revolution Brings Real-Time AI to Billions of Devices', summary: 'A new generation of edge AI processors has brought powerful machine learning capabilities to everyday devices, eliminating cloud dependency for most tasks.', body: 'The era of cloud-dependent AI is coming to an end. A new wave of edge processors, capable of running sophisticated language models and vision systems locally, has transformed how consumers interact with technology. Smartphones, home appliances, vehicles, and industrial sensors now process data on-device with zero latency.\n\nIndustry analysts estimate that 80% of AI inference now happens at the edge rather than in the cloud, a complete reversal from the 2020s. The shift has raised privacy standards dramatically, as personal data no longer needs to leave the device. "The edge revolution is about putting intelligence back where it belongs—in the hands of users," said Dr. Aiko Tanaka, chief architect of the Edge-Net protocol.\n\nChallenges remain in standardizing the fragmented edge ecosystem, but the trajectory is clear: the cloud is becoming a backbone for training and synchronization, not real-time intelligence.', confidence: 82, confidenceExplanation: 'Edge AI hardware is advancing rapidly with dedicated NPUs now standard in consumer devices.' },
  ],
  'Business': [
    { title: 'The Four-Day Workweek Becomes Law Across the European Economic Bloc', summary: 'In a historic vote, the European Parliament has mandated a 32-hour maximum workweek, citing AI productivity gains and improved quality of life.', body: 'The European Economic Bloc has made history by passing the Work-Life Balance Act, which limits the legal workweek to 32 hours across all member states. The law, which takes effect in January 2042, is the culmination of a two-decade movement accelerated by artificial intelligence\'s dramatic impact on workplace productivity.\n\nSupporters point to pilot programs in Iceland, Spain, and Germany that showed no reduction in output when workers shifted to four-day schedules. "AI has eliminated so much busywork that we\'re essentially paying people to be present, not productive," said European Commissioner for Digital Affairs Sofia Bergström. "This law aligns our labor framework with technological reality."\n\nBusiness groups are divided. While many tech companies have already adopted flexible schedules, traditional industries like manufacturing and hospitality argue that coverage requirements make the mandate impractical.', confidence: 81, confidenceExplanation: 'The four-day workweek movement has strong momentum globally, with numerous successful trials.' },
    { title: 'Global Stock Exchanges Merge Into Single 24/7 Digital Trading Network', summary: 'The world\'s major stock exchanges have completed a landmark merger into a unified global trading platform that operates around the clock.', body: 'In a move that reshapes global finance, the world\'s twelve largest stock exchanges have completed their merger into the Global Digital Exchange (GDX), a unified platform that never closes. The merger, years in the making, eliminates time-zone barriers and creates a truly continuous market.\n\nTrading volumes have surged 300% since the merger, with cross-border investment flows increasing dramatically. The GDX uses a distributed ledger system that settles trades in real-time, eliminating the traditional T+2 settlement cycle. "This is the end of sleeping on your portfolio," said GDX CEO Maria Okonkwo. "The market is always open, always liquid, and always fair."\n\nRegulators have imposed circuit breakers and algorithmic trading limits to prevent flash crashes in the always-on environment. Early results show reduced volatility compared to the old system.', confidence: 63, confidenceExplanation: 'Exchange consolidation is a long-term trend, but a full merger faces significant regulatory and technical hurdles.' },
    { title: 'Universal Basic Income Pilot Expands to 30 Countries as Automation Displaces Jobs', summary: 'A coordinated international UBI experiment now covers 500 million people, providing a monthly stipend funded by AI productivity taxes.', body: 'The world\'s largest social experiment has reached a new milestone. The Global UBI Initiative, a partnership of 30 nations, now provides monthly payments to 500 million citizens. The program is funded primarily through a "productivity dividend tax" on companies that replace human workers with AI systems.\n\nEarly results show mixed outcomes. While poverty rates have dropped 40% in participating regions, concerns about inflation and workforce participation persist. "People are using the stipend for education, starting small businesses, and caregiving," said Dr. James Park, the initiative\'s research director. "The fear that people would simply stop working has not materialized."\n\nCritics argue the program is unsustainable without dramatic tax increases, while supporters counter that the cost of not implementing UBI—social unrest, inequality, and reduced consumption—would be far higher.', confidence: 71, confidenceExplanation: 'UBI pilot programs are expanding globally, but large-scale implementation faces political and economic obstacles.' },
    { title: 'Cryptocurrency Replaces National Currencies in Five Nations as Inflation Hedge', summary: 'Five countries have adopted decentralized digital currencies as legal tender, citing protection against inflation and financial inclusion.', body: 'The cryptocurrency experiment has reached a new frontier. Five nations—El Salvador, Paraguay, Senegal, Fiji, and Estonia—have adopted decentralized digital currencies as official legal tender, replacing or supplementing their national currencies. Unlike earlier attempts, these adoptions are backed by comprehensive regulatory frameworks and consumer protections.\n\nThe shift was driven by inflation rates that eroded faith in traditional currency. "When your savings lose 15% of their value annually, a volatile cryptocurrency starts to look stable by comparison," said Finance Minister Karl Johansson of Estonia.\n\nThe International Monetary Fund has expressed concern about financial stability, but early economic indicators in adopting nations show increased foreign investment and remittance flows.', confidence: 48, confidenceExplanation: 'Cryptocurrency adoption is unpredictable and depends on complex economic and political factors.' },
  ],
  'Science': [
    { title: 'Fusion Energy Achieves Grid Parity: Commercial Plants Now Cheaper Than Solar', summary: 'Helion Energy\'s seventh-generation fusion reactor has reached a levelized cost of $18 per MWh, undercutting every other energy source in history.', body: 'The fusion revolution is no longer coming—it has arrived. Helion Energy announced today that its newest fusion plant in Nevada has achieved a levelized cost of energy (LCOE) of $18 per megawatt-hour, making it cheaper than solar ($22/MWh), wind ($20/MWh), and dramatically cheaper than natural gas ($45/MWh) or coal ($65/MWh).\n\n"What we\'ve done is build a sun in a box, and now we\'ve made it cheaper than the real sun," said Helion CEO Dr. Sarah Chen. The plant uses a boron-hydrogen fuel cycle that produces no neutrons, meaning virtually no radioactive waste.\n\nThe implications for climate change are staggering. Twelve nations have already signed agreements to phase out fossil fuel power plants entirely by 2045. Fusion-powered desalination is expected to solve water scarcity in arid regions, and fusion-powered cargo ships are already in prototype.', confidence: 55, confidenceExplanation: 'Fusion has made technical progress but commercial viability timelines remain speculative.' },
    { title: 'CRISPR Therapy Eliminates Sickle Cell Disease Worldwide in Largest Public Health Campaign', summary: 'A coordinated global effort has administered gene-editing treatments to 50 million people, effectively eliminating sickle cell disease as a public health threat.', body: 'The World Health Organization has declared sickle cell disease eliminated as a global public health threat, thanks to an unprecedented 15-year campaign that brought CRISPR-based gene therapy to 50 million patients across 90 countries.\n\nThe treatment, which costs just $200 per dose in its latest formulation, corrects the single-point mutation responsible for the disease. Mobile clinics equipped with automated gene-editing systems traveled to the most remote regions. "This proves that advanced biotechnology can serve everyone, not just the wealthy," said WHO Director-General Dr. Amara Osei.\n\nThe campaign has become a model for tackling other genetic disorders, with cystic fibrosis and Huntington\'s disease next in line.', confidence: 76, confidenceExplanation: 'CRISPR therapies are advancing rapidly and cost reductions for genetic treatments follow predictable curves.' },
    { title: 'Mars Colony Surpasses 10,000 Residents as Permanent Settlement Takes Shape', summary: 'The first permanent human settlement on Mars has reached a population of 10,000, with full food and water self-sufficiency achieved.', body: 'Mars colony Alpha Prime has reached a historic milestone: 10,000 permanent residents living in a fully self-sufficient settlement. The colony, established in 2038, now produces its own food through hydroponic farms, extracts water from subsurface ice, and manufactures building materials from Martian regolith.\n\n"Ten thousand people living on another planet—this is the moment humanity became multiplanetary," said colony director Dr. Kenzo Nakamura. The settlement spans four interconnected domes with a total area of 2 square kilometers.\n\nChallenges remain. Radiation exposure is still higher than Earth-normal, and psychological studies show that 15% of long-term residents experience significant isolation effects. A fifth dome, dedicated to zero-gravity manufacturing, is under construction.', confidence: 62, confidenceExplanation: 'Space colonization timelines are highly uncertain but private sector investment has accelerated development significantly.' },
    { title: 'Quantum Computing Breaks Classical Encryption: Internet Infrastructure Undergoes Emergency Upgrade', summary: 'A quantum computer has successfully broken RSA-2048 encryption, triggering the largest coordinated infrastructure upgrade in internet history.', body: 'The cryptographic foundation of the internet has been shattered. Researchers at the Swiss Federal Institute of Technology demonstrated the first successful factorization of a 2048-bit RSA key using a 10,000-qubit quantum processor. The achievement, long anticipated by cryptographers, has triggered an emergency global transition to post-quantum cryptography.\n\n"This is not a surprise—we\'ve known this day was coming for decades," said Dr. Nina Patel, chair of the Global Cryptography Council. "What matters now is how quickly we can deploy quantum-resistant algorithms."\n\nMajor technology companies and governments have activated contingency plans developed over the past 15 years. The transition is expected to take 18 months and cost an estimated $500 billion, but the alternative—leaving global communications vulnerable—is unthinkable.', confidence: 58, confidenceExplanation: 'Quantum computing progress follows exponential curves but the exact timeline for breaking RSA-2048 is uncertain.' },
  ],
  'Climate': [
    { title: 'Great Green Wall Stretches Across the Sahel: 8,000 Kilometers of Restored Land', summary: 'Africa\'s ambitious reforestation project has surpassed all expectations, restoring 100 million hectares of once-barren land and transforming regional climate patterns.', body: 'Twenty years after its launch, the Great Green Wall initiative has achieved what many called impossible. An 8,000-kilometer belt of restored vegetation now stretches across the entire Sahel region, from Senegal in the west to Djibouti in the east. The project has restored 100 million hectares of degraded land—an area larger than Egypt.\n\nThe results have been transformative. Regional rainfall has increased by 25% in restored areas. Twenty million families have regained food security. And carbon sequestration now absorbs 250 million tons of CO2 annually.\n\n"The Great Green Wall proves that we can reverse desertification at continental scale," said Dr. Amina Ouedraogo, the project\'s director. "It required unprecedented cooperation between 22 nations, but the return on investment has been extraordinary."', confidence: 85, confidenceExplanation: 'Based on the existing Great Green Wall initiative\'s current progress and increasing international funding.' },
    { title: 'Atmospheric Carbon Capture Reaches 2 Gigatons Annually as 500 Plants Go Online', summary: 'The world\'s largest network of direct air capture plants is now removing 2 billion tons of CO2 from the atmosphere each year.', body: 'Direct air capture (DAC) has scaled from a niche technology to a major climate intervention. A global network of 500 DAC plants now removes 2 gigatons of CO2 annually—equivalent to 5% of global emissions. The largest facility, in the Sahara Desert, captures 50 megatons per year using solar-powered chemical filters.\n\nThe cost has fallen from $600 per ton in 2025 to just $50 per ton today, driven by manufacturing scale and improved sorbent materials. "At $50 a ton, carbon removal is cheaper than most emissions avoidance strategies," said Dr. Lars Green, CEO of CarbonCollect.\n\nEnvironmental groups remain divided, with some arguing that carbon removal distracts from emissions reduction. However, climate scientists are clear: both are needed.', confidence: 73, confidenceExplanation: 'DAC technology costs are falling rapidly and investment in carbon removal has grown 50x in the past decade.' },
    { title: 'Arctic Ice Returns Year-Round After Decade of Geoengineering', summary: 'A coordinated program of stratospheric aerosol injection and ice restoration has brought year-round Arctic ice cover back for the first time since 2040.', body: 'In a stunning reversal, the Arctic Ocean has maintained ice cover throughout the entire year for the first time in over two decades. The achievement is the result of the Arctic Restoration Project, a geoengineering program that combines stratospheric aerosol injection with autonomous ice-thickening drones.\n\n"We didn\'t just slow the decline—we reversed it," said project lead Dr. Helga Lindström. The program, costing $40 billion annually and funded by 30 nations, has reduced regional temperatures by 2 degrees Celsius.\n\nThe success has reignited the global debate about geoengineering. While Arctic restoration is widely celebrated, critics warn that uncoordinated geoengineering could have unpredictable side effects. An international governance framework for climate intervention is now being drafted at the UN.', confidence: 41, confidenceExplanation: 'Geoengineering remains controversial and its effectiveness and side effects are highly uncertain at scale.' },
    { title: 'Vertical Farming Supplies One-Third of Global Vegetables as Agriculture Goes Indoors', summary: 'Vertical farms now produce 35% of the world\'s vegetables, reducing land use by 95% and water consumption by 90% compared to traditional agriculture.', body: 'The agricultural revolution has moved indoors. Vertical farms—multi-story facilities using LED lighting and hydroponic systems—now supply 35% of the world\'s vegetables, up from just 5% in 2025. The largest facility, in Singapore, produces 50,000 tons of vegetables annually on a footprint the size of two football fields.\n\n"The future of farming is vertical, urban, and automated," said Dr. Raj Mehta, CEO of GreenTower Industries. Robots handle planting, monitoring, and harvesting, while AI optimizes light spectra and nutrient delivery for each crop variety.\n\nThe shift has freed 200 million hectares of farmland for rewilding and carbon sequestration. Traditional farmers have faced disruption, but retraining programs have helped many transition to indoor agriculture.', confidence: 79, confidenceExplanation: 'Vertical farming has achieved economic viability and is scaling rapidly, supported by declining LED costs.' },
  ],
  'World': [
    { title: 'Global Digital Currency Initiative Reaches 120 Nations as Cash Use Declines 80%', summary: 'The World Digital Currency, a supranational digital tender backed by a coalition of 120 nations, has become the most widely used currency on Earth.', body: 'In a transformation that central bankers once dismissed as impossible, digital currency has become the dominant form of money worldwide. The World Digital Currency (WDC), launched in 2038 by a coalition of 120 nations, now accounts for 67% of all global transactions.\n\nPhysical cash usage has declined by 80% since 2025, with many nations operating entirely cashless economies. The WDC system uses a two-tier architecture: a central blockchain managed by the coalition\'s central bank, and private licensed intermediaries that handle consumer-facing services.\n\nCritics warn of surveillance risks, as every transaction is recorded on the public ledger. Several nations have implemented zero-knowledge proof layers that hide transaction details while maintaining auditability.', confidence: 70, confidenceExplanation: 'CBDC development is accelerating globally with over 100 nations exploring digital currencies.' },
    { title: 'High-Speed Rail Network Now Connects Every Capital City in Continental Europe', summary: 'The Trans-European Rail Network has achieved full connectivity, linking all 44 European capital cities with trains exceeding 600 km/h.', body: 'European integration has reached a new milestone with the completion of the Trans-European Rail Network (TERN). For the first time in history, every continental European capital is connected by high-speed rail, with travel times between any two capitals not exceeding 12 hours.\n\nThe network uses magnetic levitation technology developed through a 25-year collaboration between 40 nations. Trains routinely reach speeds of 600 km/h, making rail competitive with air travel for routes up to 2,000 kilometers. Passenger numbers have exceeded projections by 40%.\n\n"TERN has done more for European unity than any treaty ever could," said EU Transport Commissioner Luca Rossi. "When you can have breakfast in Paris and lunch in Warsaw, borders become meaningless."', confidence: 77, confidenceExplanation: 'High-speed rail expansion continues across Europe and maglev technology has matured significantly.' },
    { title: 'Global Population Stabilizes at 9 Billion as UN Declares Demographic Transition Complete', summary: 'The United Nations has declared that the global population has stabilized at 9 billion, marking the completion of the demographic transition.', body: 'For the first time in modern history, the global population has stopped growing. The UN Population Division announced today that the world population has stabilized at 9 billion, with fertility rates at or below replacement level in every major region.\n\nThe milestone, long predicted by demographers, arrived earlier than most models anticipated. "The demographic transition is complete," said UN Secretary-General Amara Diallo. "We have reached population stability through choice, not coercion."\n\nThe implications are profound. Aging populations in former high-fertility regions will reshape economies, healthcare systems, and migration patterns. Some nations are already implementing pro-natalist policies to maintain workforce levels, while others focus on productivity gains through automation.', confidence: 88, confidenceExplanation: 'Population projections are among the most reliable demographic forecasts, and current trends strongly indicate stabilization.' },
    { title: 'Autonomous Drone Delivery Networks Cover 90% of Urban Areas Worldwide', summary: 'A global network of autonomous delivery drones now serves 90% of urban areas, with delivery times averaging under 30 minutes.', body: 'The skies above the world\'s cities have become a silent highway of delivery drones. A coordinated network of autonomous aerial vehicles, managed by AI traffic control systems, now handles 15 billion deliveries annually. Packages range from meals to medical supplies to consumer goods.\n\nThe system uses designated air corridors at altitudes between 100 and 300 meters, with drones automatically negotiating priority and routing. "The noise complaints we feared never materialized because these drones are virtually silent," said Urban Air Management Authority director Carmen Ruiz.\n\nPrivacy advocates have raised concerns about surveillance capabilities, but operators counter that the drones\' cameras are only active for navigation. The industry has self-regulated with "privacy mode" standards.', confidence: 80, confidenceExplanation: 'Drone delivery is already operational in dozens of cities and continues to scale rapidly with regulatory approval.' },
  ],
  'Health': [
    { title: 'AI Primary Care: Machines Now Diagnose More Accurately Than Human Doctors in 95% of Cases', summary: 'A landmark 10-year study confirms that AI diagnostic systems outperform human physicians across nearly all common conditions, reshaping healthcare delivery worldwide.', body: 'The largest clinical study in medical history has reached a definitive conclusion: AI diagnostic systems are now more accurate than human physicians in 95% of common medical conditions. The study tracked 50 million patient encounters across 2,000 clinics in 30 countries over 10 years.\n\nAI systems achieved a 97.3% diagnostic accuracy rate compared to 89.1% for human physicians. The AI was particularly superior in dermatology (99.1% vs 86.2%), radiology (98.7% vs 87.3%), and early detection of rare conditions.\n\nRather than replacing doctors, the healthcare system has evolved into a partnership model. AI handles initial diagnosis and routine care, while human physicians focus on complex cases, surgical procedures, and the empathetic aspects of patient care.', confidence: 88, confidenceExplanation: 'AI diagnostic accuracy has already matched or exceeded humans in specific domains with regulatory approval accelerating.' },
    { title: 'Personalized mRNA Vaccines Now Annual and Tailored to Individual Genetics', summary: 'A new generation of mRNA vaccines is customized to each individual\'s genetic profile and administered annually to prevent dozens of diseases simultaneously.', body: 'The mRNA revolution has entered its next phase. Personalized mRNA vaccines, designed using each individual\'s genomic data, now provide protection against 30 respiratory viruses, 12 cancers, and 8 autoimmune conditions in a single annual injection.\n\nThe vaccines are manufactured on-demand at local pharmacies using portable mRNA printers. A patient\'s genetic data, collected via a simple cheek swab, informs the exact antigen selection. "This is the ultimate personalization of medicine," said Dr. Elena Vos, chief medical officer at GeneVax. "Your immune system gets exactly the training it needs."\n\nThe program has reduced hospitalizations from vaccine-preventable diseases by 90% in participating countries. The cost has dropped to $150 per person annually, making it accessible in middle-income nations.', confidence: 74, confidenceExplanation: 'mRNA platform technology is adaptable and the cost of genomic sequencing continues to decline exponentially.' },
    { title: 'Bionic Eyes Restore Sight to 5 Million People with Advanced Neural Implants', summary: 'A new generation of bionic eye implants has restored functional vision to 5 million blind individuals using direct neural interfaces.', body: 'The age of blindness is ending. A bionic eye implant developed by NeuroSight Corporation has restored functional vision to 5 million people worldwide. The implant, which replaces the damaged retina with a neural interface chip, connects directly to the optic nerve, bypassing non-functional photoreceptors.\n\nThe latest generation provides 20/40 vision—good enough to read, drive, and recognize faces. "I saw my daughter\'s face for the first time today," said patient Marcus Johnson, who lost his sight at age 12. "The colors were more vivid than I ever imagined."\n\nThe procedure costs $15,000 and is covered by insurance in 40 countries. Researchers are already working on enhancements that could provide better-than-natural vision, including night vision and zoom capabilities.', confidence: 69, confidenceExplanation: 'Neural interface technology is advancing rapidly with multiple successful clinical trials reported.' },
    { title: 'World Health Organization Declares Cancer Mortality Reduced by 70% Through Early Detection', summary: 'A combination of liquid biopsy screening and AI-powered diagnostics has reduced global cancer mortality by 70%, the largest single improvement in medical history.', body: 'The war on cancer has achieved its most significant victory. Annual liquid biopsy screening—a simple blood test that detects cancer DNA years before symptoms appear—combined with AI-powered treatment planning has reduced global cancer mortality by 70%.\n\nThe screen, which costs just $50, detects 50 cancer types simultaneously with 99.5% accuracy. Early detection means that most cancers are now caught at Stage I or Stage II, when treatment success rates exceed 95%. "Cancer is no longer a death sentence—it\'s a manageable condition," said Dr. Wei Chang, director of the Global Cancer Institute.\n\nTreatment has also transformed. AI-designed personalized therapies and targeted immunotherapies have reduced chemotherapy use by 80%, dramatically improving quality of life during treatment.', confidence: 83, confidenceExplanation: 'Liquid biopsy technology is already clinically validated and costs are following predictable reduction curves.' },
  ],
  'Sports': [
    { title: 'Holographic Stadiums Bring Global Audiences Into Live Sports Experiences', summary: 'A new generation of holographic projection technology allows millions of fans to experience live sporting events from any location as if they were in the stadium.', body: 'The era of watching sports on screens is giving way to something far more immersive. Holographic Sports Technologies (HST) has deployed its HoloStadium system in 45 major venues worldwide, allowing up to 500,000 remote viewers per event to experience the game as three-dimensional holographic projections in local viewing centers.\n\nThe technology uses thousands of tiny projectors and LiDAR sensors to create real-time, full-scale holographic reconstructions of every player and the ball. "Being able to walk around a holographic quarterback and see the game from his perspective—it\'s revolutionary," said NFL Commissioner Jamal Williams.\n\nTicket sales for physical attendance have actually increased, as the in-person experience remains distinct, while the holographic option has expanded the total audience by 400%.', confidence: 60, confidenceExplanation: 'Holographic display technology is advancing but large-scale deployment faces cost and infrastructure hurdles.' },
    { title: 'AI Referee System Eliminates Human Error in All Major Sports Leagues', summary: 'An AI-powered officiating system adopted by every major sports league has eliminated referee errors, reducing controversy and improving fairness.', body: 'The age of disputed calls and referee controversies is over. Every major sports league worldwide has adopted the Universal Officiating System (UOS), an AI-powered platform that makes real-time calls with 99.99% accuracy.\n\nThe system uses a network of 200 synchronized cameras and millimeter-wave sensors to track every movement on the field. Decisions are rendered in under 200 milliseconds and displayed to audiences instantly. "The human element in officiating is now a thing of the past," said FIFA President Carla Moreno.\n\nWhile some fans miss the human drama of controversial calls, player safety has improved dramatically. The system detects dangerous play that human referees often miss, reducing serious injuries by 35% across all sports.', confidence: 75, confidenceExplanation: 'Computer vision technology is already used in limited officiating roles and continues to improve rapidly.' },
    { title: 'Olympic Games Expanded to Include 20 New Sports as Virtual Events Debut', summary: 'The International Olympic Committee has added 20 new sports including drone racing, neural gaming, and augmented reality marathons.', body: 'The Olympic Games have undergone their most dramatic transformation in a century. The IOC has approved 20 new sports for the 2048 Games, including 8 virtual and augmented reality disciplines that blur the line between physical and digital athletics.\n\nDrone racing through obstacle courses, neural gaming (thought-controlled competitions), and augmented reality marathons that overlay digital obstacles onto real-world courses are among the new events. "We are meeting athletes where they are—the boundary between physical and digital sport no longer exists," said IOC President Thomas Bach.\n\nTraditionalists have criticized the changes, arguing that virtual disciplines dilute the Olympic spirit. But viewership among under-30 demographics has increased 200% since the announcement.', confidence: 66, confidenceExplanation: 'The IOC has already shown willingness to add esports and digital events, and youth engagement trends support further expansion.' },
    { title: 'Human Augmentation Creates New Paralympic Records, Outpacing Pre-Augmentation Able-Bodied Records', summary: 'Paralympic athletes using advanced bionic prosthetics have surpassed pre-augmentation Olympic records, sparking debate about the future of sport.', body: 'A historic moment in sport: Paralympic sprinter Maria Costa, running on carbon-fiber neural-integrated prosthetics, has broken the pre-2030 Olympic 100m world record with a time of 9.42 seconds. The achievement has ignited a global debate about the role of technology in human performance.\n\n"This is not human versus human anymore—it\'s human plus technology," said sports ethicist Dr. James Whitfield. The International Paralympic Committee has established three competition categories: biological (no augmentation), assisted (standard prosthetics), and open (any augmentation).\n\nThe debate has reached the Olympic committee, with some calling for a separate "augmented Olympics" category. Others argue that all sport is technologically mediated and that this is simply the next step.', confidence: 52, confidenceExplanation: 'Bionic technology is advancing rapidly but the pace of regulatory adaptation in sport is uncertain.' },
  ],
  'Entertainment': [
    { title: 'AI-Generated Film Wins Academy Award for Best Picture in Historic First', summary: 'The film "Echoes of Tomorrow," created entirely by generative AI with no human writers or directors, has won the Oscar for Best Picture, sparking intense debate about the nature of art.', body: 'The Academy of Motion Picture Arts and Sciences made history last night by awarding the Best Picture Oscar to "Echoes of Tomorrow," a film generated entirely by artificial intelligence. The movie, created by the AI system Muse v4.0, had no human writers, directors, or cinematographers.\n\nThe film tells the story of humanity\'s last day before a cosmic event erases time, exploring themes of memory, love, and loss through a non-linear narrative. The victory has reignited debates about the definition of art and the role of human creativity.\n\n"This is not the end of human filmmaking, but a new medium to explore," said the CEO of Muse Studios, accepting the award. "AI doesn\'t replace human creativity—it democratizes it, making cinematic storytelling accessible to anyone with a vision."', confidence: 45, confidenceExplanation: 'AI-generated content is advancing but critical acceptance remains uncertain and culturally dependent.' },
    { title: 'Holographic Concerts Generate $50 Billion as Living Legends Perform Alongside Digital Resurrection', summary: 'The live music industry has transformed with holographic performances generating $50 billion annually, including concerts by digital recreations of deceased artists.', body: 'The live music industry has undergone a holographic revolution. Holographic concerts—where artists perform as real-time 3D projections—now generate $50 billion annually, surpassing traditional live performances. The technology allows a single artist to perform in 20 cities simultaneously.\n\nDigital resurrections of deceased musicians, created from training AI models on their complete body of work, have proven controversial but immensely popular. A recent "tour" by a digital recreation of Freddie Mercury sold out arenas worldwide. "It\'s not a replacement, it\'s a continuation," said the estate\'s spokesperson.\n\nUnions have negotiated strict rules around digital performers, including profit-sharing with living artists whose styles are used in training data. The ethical framework for posthumous digital performance remains a work in progress.', confidence: 58, confidenceExplanation: 'Holographic concert technology already exists and is commercially viable, but digital resurrection is ethically complex.' },
    { title: 'Interactive AI Narratives Allow Viewers to Shape Storylines in Real-Time', summary: 'A new streaming platform lets viewers influence plot outcomes through voice commands and emotional responses, creating personalized story experiences.', body: 'Passive entertainment is giving way to interactive storytelling. StreamVerse, a new platform launched by a consortium of studios, offers films and series where viewers can influence plot outcomes in real-time through voice commands, facial expressions, and even biometric responses.\n\nThe AI narrative engine generates branching storylines that adapt to viewer reactions. "We\'re not just watching a story—we\'re living it," said StreamVerse CEO Anita Patel. A romantic comedy might change its ending based on whether the viewer smiles at certain moments. A thriller might intensify if the viewer\'s heart rate rises.\n\nCritics argue that surrendering narrative control diminishes the artist\'s vision. But early data shows that interactive episodes have 3x the rewatch rate of traditional linear content.', confidence: 64, confidenceExplanation: 'Interactive storytelling is already prevalent in gaming and AI advances make real-time narrative adaptation feasible.' },
    { title: 'Virtual Influencers Command Larger Audiences Than Human Celebrities', summary: 'AI-generated virtual personalities now occupy the top 20 spots on global influencer rankings, with engagement rates 5x higher than human counterparts.', body: 'The most popular influencers on Earth are not human. AI-generated virtual personalities—with meticulously crafted appearances, personalities, and backstories—now occupy the top 20 positions on the Global Influence Index. The leading virtual influencer, Luna-7, has 800 million followers.\n\nVirtual influencers never age, never make offensive remarks, and are available 24/7 for brand partnerships. Their engagement rates average 15%, compared to 3% for human influencers. "Brands love the predictability and consistency," said marketing analyst Dr. Karen Wu.\n\nThe rise has created a crisis for human influencers, many of whom have augmented themselves with AI filters and virtual enhancements to compete. The line between real and virtual has blurred to the point where most followers cannot tell the difference.', confidence: 70, confidenceExplanation: 'Virtual influencers already exist with millions of followers, and the trend toward AI-generated personalities is accelerating.' },
  ],
}

const usedSlugs = new Set()

function uniqueSlug(title) {
  let slug = slugify(title)
  let base = slug
  let i = 1
  while (usedSlugs.has(slug)) {
    slug = `${base}-${i}`
    i++
  }
  usedSlugs.add(slug)
  return slug
}

function generateMockArticle(category, futureDate) {
  const articles = MOCK_ARTICLES[category] || MOCK_ARTICLES['Technology']
  const article = articles[Math.floor(Math.random() * articles.length)]
  return {
    ...article,
    slug: uniqueSlug(article.title),
    category,
    futureDate,
  }
}

async function generateArticle({ futureDate, category, trends }) {
  if (config.isMockMode) {
    return generateMockArticle(category, futureDate)
  }

  const yearsAhead = parseInt(futureDate.split('-')[0], 10) - new Date().getFullYear()
  const trendContext = trends.map(t => `- ${t}`).join('\n')

  const prompt = `You are a journalist writing for "The Future Times," a newspaper that reports on future events as if they have already happened.
The current year is ${futureDate}, ${yearsAhead} years from today.

Category: ${category}

Relevant trends and context for this future:
${trendContext}

Write a news article from the year ${futureDate} in the ${category} category. The article should:
1. Sound like a real newspaper article from a reputable publication
2. Reference specific dates, technologies, policies, or events that could plausibly exist
3. Include quotes from experts, officials, or studies
4. Mention both achievements and ongoing challenges
5. Be 3-5 paragraphs long

Return valid JSON only with these fields:
- "title": a compelling headline
- "summary": a one-sentence summary
- "body": the full article text (3-5 paragraphs, each separated by \\n\\n)
- "confidence": a number 0-100 indicating how confident this prediction is
- "confidenceExplanation": a brief explanation of what factors support this prediction`

  try {
    const response = await generateCompletion([{ role: 'user', content: prompt }], {
      temperature: 0.85,
      maxTokens: 2048,
    })
    if (!response) throw new Error('Empty response from Groq')
    const parsed = JSON.parse(response)
    return {
      title: parsed.title,
      slug: uniqueSlug(parsed.title),
      category,
      summary: parsed.summary,
      body: parsed.body,
      confidence: Math.min(100, Math.max(0, parsed.confidence || 50)),
      confidenceExplanation: parsed.confidenceExplanation || '',
      futureDate,
    }
  } catch (err) {
    console.error(`Article generation error for ${category}:`, err.message)
    return generateMockArticle(category, futureDate)
  }
}

module.exports = { generateArticle, MOCK_ARTICLES, resetUsedSlugs: () => { usedSlugs.clear() } }
